# Generated by Django 4.0.8 on 2024-03-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_options_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('title',), 'verbose_name': 'Bloq', 'verbose_name_plural': 'Bloqlar'},
        ),
    ]
